### ISSUE TITLE
New kernel version available?

### ISSUE THREAD

**Issue by sjoerdboerhout** [WAGO/pfc-firmware-sdk#15]
Current kernel version in this repo seems to be 4.9. Any plans to use a more recent kernel version?

**Comment by Helmut-Saal** [comment]
Changing Kernel is not so easy because of the rt patch. Wy do you need an different version?

**Comment by sjoerdboerhout** [comment]
Well we are currently looking for a PLC running Linux to migrate our current hardware and C/C++ based software platform. We have to support it for +/- 10 years so updates are part of my requirements.
For example the Beckhof CX9020 is available with kernel 4.19 which is about 2 years newer than the kernel used for this Wago plc.

**Comment by Helmut-Saal** [comment]
Hello, I understand that. We update our firmware 4 times a year, this includes for example the C++ compiler. We also update a kernel if we can guarantee the function on our devices. The firmware and functions on our devices are complex, so sometimes our packages are not "up to date". But we try to keep the firmware contours the same so that updates are possible for many years.
BG
