### ISSUE TITLE
Propose to upgrade OpenSSL v1.1.1

### ISSUE THREAD

**Issue by lordtct** [WAGO/pfc-firmware-sdk#18]
At the time of this writing, the OpenSSL.make rule calls for version 1.0.2u, whose Long Term Support ended in Dec 2019.
The latest ptxdist (2012.08) is already using OpenSSL 1.1.1k, which should be supported until end 2023.

Since WAGO is actively touting PFC and Edge series as IoT-friendly controllers, it would be a shame if it is still using outdated cipher suites with no X25519, CCM or TLS 1.3 support.

**Comment by Helmut-Saal** [comment]
Hello, you may have partial right but, the support for security for version 1.0.2 is not stopped! It ist not so easy to upgrade libs so fast because we have to make sure that the device works 24/7/365 as a PLC (with RT patch) because that ist the main task for the controller. Also we have to check that all licenses will fit, all dependencys and some other stuff to guarantee the function. We will upgrade this lib with FW20 to 1.1.1. 
But feel free to build your own firmware with the sdk, that ist the reason wy will provide the tool.  :-)
